### ISSUE TITLE
UI to allow modifying the filters and sorts for the current collection

### ISSUE THREAD

**Issue by jkomoros** [jkomoros/card-web#498]
There should be UI to modify the currently active collection description.

It would be... non-trivial.

Basically it should allow creating and editing all of the sorts and filters documented in the wiki.

A number of the filters are straightforward:

* Sections
* Tags
* TODOs

You'd also want union filters

But then for all of the other configurable functions there are arbitrarily complex UIs necessary for each.

**Comment by jkomoros** [comment]
Maybe have a 'Edit Collection' button in the card drawer overflow that opens up a dialog that allows you to modify the collection and navigate to the new collection.

This issue is likely a dupe of an older one.

The state would likely store a collection description, but then doesn't the canonicalization lose information about the order of pieces? That could lead to UI in the dialog jumping around.

**Comment by jkomoros** [comment]
`exclude` and `combine` will need special treatment

**Comment by jkomoros** [comment]
- [ ] Add description field to SET_INFOs

**Comment by jkomoros** [comment]
To get the performance to be OK there should be a activeCollection and snapshotCollection, where 
```
			activeSetName: action.setName,
			activeFilterNames: [...action.filters],
			activeSortName: action.sortName,
			activeSortReversed: action.sortReversed,
			activeViewMode: action.viewMode,
			activeViewModeExtra: action.viewModeExtra,
```
Is all filtered out into a new type, and there's a 'snapshot' method. Then CollectionDescription could just selectActiveCollectionConfiguration and pass each property into CollectionDescription (which could have a concstructor that also takes an object of that shape (the current selectActiveSetName etc don't get used for anything other than selectActiveCollectionDescription anyyway

**Comment by jkomoros** [comment]
## Audit notes: `codex/collection-composer-polish`

Ran the branch (worktree of `c2fa90d3`, dogfood mode, live corpus, 1307 cards, previews enabled) and read the diff. Everything below was reproduced in a running build unless explicitly marked otherwise. All 151 new tests pass individually on Node 20; none of them catch the four blocking items.

Filing as a checklist so the actionable bits live here.

---

### Blocking

- [ ] **`snack-bar` can never become visible — every navigation receipt, the Undo, and both copy-link confirmations are dead UI.** `active` is declared `@property({type: Boolean})` with no `reflect: true`, but visibility is styled off `:host([active])`. Verified: `sb.active = true; await sb.updateComplete` → `getAttribute('active') === null`, `visibility: hidden`. Pre-existing defect (same binding on `master`, where the only consumer was the offline toast), but this branch builds four new user-facing behaviors on it and restyles it (`z-index`, `max-width`) as if it worked. The whole "reversible collection navigation receipts" commit currently has no visible output. — `src/components/snack-bar.ts:7`, `:33`

- [ ] **Ctrl-K → Tab → Enter does nothing.** Enter opens the *highlighted suggestion*, not the draft. After any Tab the list rebuilds at `_highlightedSuggestion = 0`, and row 0 is a recent — "Back to Main" — because `recentSuggestions` dedupes against the *draft* rather than the *active* collection, so the collection you're standing in is always offered as a destination. Enter then hits the `alreadyActive` short-circuit and closes the dialog silently, discarding the clause.
  ```
  Ctrl-K → type "systems" → Tab   draft = Main AND Tagged Systems Theory
                                  row 0 = "Back to Main" (OPEN)
  Enter                           dialog closes, path still /c/main/, clause discarded, no message
  ```
  Three separable fixes: (a) Enter should target the draft, or the primary action should be visually distinct from row 0; (b) dedupe recents against the active description; (c) the already-active path needs feedback instead of a silent close. Any one alone still leaves the flow wrong. — `src/components/configure-collection-dialog.ts:1364`, `:1383`; `src/collection-composer-suggestions.ts:261`

- [ ] **The date filter editor displays `Before` while adding `after`.** Catalog → Updated seeds `updated/after/7-days-ago`; the comparison `<select>` renders at `selectedIndex 0` (`before`). Confirming adds `after`.
  ```
  _pendingCatalogFilter : "updated/after/7-days-ago"
  comparison <select>   : value "before", selectedIndex 0, options [before, after, between]
  → filters: ["updated/after/7-days-ago"]
  ```
  Same desync in the clause editor, where the header and control contradict each other side by side: **"Editing Updated since 7 days ago"** above a dropdown reading **"Before"**. Cause is the Lit ordering trap — `<select .value=${typ}>` with its `<option>`s from the same template, so the property is assigned to an empty select and dropped. Pattern predates this branch and was harmless while the only entry point started at the default; seeding a non-default value turns it into a visible lie. Fix by setting `.value` after options exist or marking the option `?selected`. — `src/components/configure-collection-date.ts:100-102` (also `:168`, `:189`, `:205`, `:222`); seeded at `configure-collection-dialog.ts:1495`

- [ ] **A stationary mouse pointer hijacks the keyboard highlight.** `@mouseenter` fires on re-render without the mouse moving, so whatever row sits under the cursor becomes what Enter does. Opening with the cursor resting at (394, 300) gave `_highlightedSuggestion = 4`, not 0; after a Tab and re-render with the cursor unmoved, 3. Gate pointer highlighting on a real `mousemove`, and suppress it for the render immediately following a keyboard action. — `configure-collection-dialog.ts:1033`

---

### Major UX

- [ ] **The default list offers the same destination twice with different verbs and different outcomes.** With previews on:
  ```
  CONTINUE
    Back to Main AND Unread    1307 cards · same number of cards   OPEN
    Back to Main AND Starred      0 cards · 1307 fewer             OPEN
  REFINE THIS COLLECTION
    Keep only Starred             0 cards · 1307 fewer             ADD
    Keep only Unread           1307 cards · same number of cards   ADD
    Keep only Working Notes       0 cards · 1307 fewer             ADD
    Start from Everything      1239 cards · 68 fewer               REPLACE
  ```
  Four of six rows are two pairs pointing at identical collections; one member navigates, the other edits the draft, and nothing explains why. Three of six lead to zero cards and two are exact no-ops — once counts exist, ranking should use them.

- [ ] **"Back to Main AND Unread · Adds Unread".** The label promises a return, the detail says it adds a filter, and neither is a going-back. `"Back to "` is prefixed to every non-frequent recent regardless of direction. — `collection-composer-suggestions.ts:267`

- [ ] **The key-hint line is wrong in most states** — it's derived from the highlighted row only, then presented as if it described the list.
  ```
  empty input, all ADD rows        "↑↓ choose · Click edits · Enter adds and opens"   (click adds, not edits)
  row 0 recent, rows 1-5 ADD       "↑↓ choose · Click or Enter opens"                (4 of 6 don't open on click)
  ```
  — `configure-collection-dialog.ts:999-1004`

- [ ] **Tab does nothing until you type.** `_handleComposerKeyDown` gates Tab on `_composerInput.trim()`, so the spec's "Tab materializes the highlighted transformation" doesn't apply in the empty state — which is the state the composer opens in. — `configure-collection-dialog.ts:1357`

- [ ] **One filter, four names.** `starred` is "Keep only Starred" (empty state), "Add Starred" (typed), "Starred" (chip), "Remove Starred" (broaden). Spec principle 3 is "a clause means the same thing everywhere it appears."

- [ ] **Editing a clause makes its name worse.** `_composerFilterLabels` only carries the hardcoded candidate filters, so any edited value falls back to `readableCollectionFilter`:
  ```
  added from catalog   "Updated since 7 days ago"
  change 7 → 14        "Updated After · 14 Days Ago"
  ```
  — `configure-collection-dialog.ts:1084`; `collection-composer-suggestions.ts:155-180`

- [ ] **Receipt copy.** `` `${action}: ${label}` `` yields **"Add: Add Starred"**; every configurable edit yields **"Updated filter"**, which reads as the noun "the Updated filter" in a product that has a filter named `updated`. — `configure-collection-dialog.ts:1412`, `:1601`

- [ ] **The catalog's largest category is the dump the spec set out to replace.** "Card properties" holds 156 alphabetised entries (six shown, rest behind "Show 150 more card properties filters"): `All Cards · Automatically Prioritized · Does Not Need Author Citation · Does Not Need Citations · … · Not Working Notes · Orphaned · Read · Unstarred`. Labels are title-cased filter IDs; every `x` / `not-x` pair is listed separately instead of offered as a polarity toggle. — `src/collection-filter-catalog.ts:11-45`

- [ ] **"Show N more `<category>` filters" is ungrammatical for every multi-word category** — "tags and sections filters", "relationships filters", "card properties filters". — `configure-collection-dialog.ts:882`

- [ ] **Catalog examples always claim you start from Everything.** With a draft of Main, every row reads `Example: Everything AND Section About`. The setup row beside it also exposes raw internal values (`main`, `default`, `list`) while the expression one line above renders "Main". — `configure-collection-dialog.ts:816-848`

- [ ] **Source mode says "Not supported here" while you're still typing the word.** Typing `star` into `/c/main/` gives status *"Not supported here — This app does not know the 'star' filter"*, while the completion list directly below correctly offers **Starred**. A partially-typed token is classified `unsupported` rather than `incomplete`, so the status reads as hard failure on nearly every keystroke; the `incomplete` copy ("Keep typing") is what this state wants. — `configure-collection-dialog.ts:633-635`; `collection-source.ts:352-357`

- [ ] **Two source-mode labels read as mismatched pairs.** "WILL OPEN AS" followed by *"Open is unavailable until the current source is valid"*; and for a valid `/c/main/`, "Will open as `http://localhost:8099/c/`" because `serializeShort` drops the default set — correct, but it reads like the app silently rewrote your input. — `configure-collection-dialog.ts:694`

- [ ] **Long lists are shown through very small windows** (measured at 800×450):

  | List | Content | Visible | Ratio |
  |---|---|---|---|
  | source completions | 843 px (12 items) | 112 px | ≈2 items |
  | filter catalog | 3,896 px (47 items) | 259 px | ≈6 items |

  Related: `scrollIntoView({block:'nearest'})` on the highlighted row scrolls the group heading permanently out of view, so once you've arrowed anywhere, row 0 shows without its **CONTINUE** label. — `configure-collection-dialog.ts:382`, `:481`, `:1671`

- [ ] **Mobile: the count column runs through the detail text.** At 375 px, `.suggestion-count` / `.suggestion-action` are `float: right` inside the same block as the wrapping detail, so the detail truncates mid-sentence behind the count ("Adds working-notes to this") and the last row is clipped by the key-hints line on top of it. Wants a grid (label / count / action), not floats. — `configure-collection-dialog.ts:424-438`

- [ ] **Navigate to an empty collection and the composer entry point disappears.** The collection summary — primary click target and the only visible mention of Ctrl-K — lives in the card drawer's `visible-info` slot, and the drawer collapses to zero width when the collection is empty. No empty-state message either. Composing into an empty collection is a normal outcome of a filtering tool and is exactly when the composer is needed most. In the drawer it's also only ~133 px wide with a 2-line clamp, so any real expression is truncated on arrival. — `src/components/card-view.ts`, `.collection-summary` block

- [ ] **Ctrl-K while the composer is open does nothing.** `card-view._handleKeyDown` returns early whenever the dialog is open, so it neither closes nor refocuses. Note the reducer carries a comment defending idempotent open ("a repeated Ctrl-K must not replace an in-progress draft") — that guard is unreachable from the keyboard. — `card-view.ts` dialog-open gate; `src/reducers/collection.ts:179`

- [ ] **"Start from Everything" shows 68 *fewer* cards, unexplained.** Verified against the engine directly, so this is a real property of the data model, not a preview bug: `/c/main/` = 1307, `/c/everything/` = 1239. Not the composer's fault, but it is the composer's problem — principle 7 promises "surprise repair", and a set change that shrinks the collection is exactly that case.

- [ ] **Closing the composer drops focus to `<body>`.** `DialogElement` captures `deepActiveElement()` as the invoker and restores on close, but when opened by Ctrl-K the active element typically isn't focusable, so `.focus()` is a no-op. Keyboard users tab from the top of the document after every cancel. The branch's own test supplies a synthetic focusable invoker, so it passes. — `dialog-element.ts:266-280`; `test/dialog-element/test.js:73`

- [ ] **Removing the clause you're editing leaves an empty editor panel.** `_removeDraftClause` resets `_selectedClauseIndex` to `-1` but leaves `_builderExpanded` true, so `_selectedClauseEditorRender` returns `''` into a still-rendered `.builder` container. — `configure-collection-dialog.ts:1428`, `:768-771`, `:1010`

---

### Robustness

- [ ] **Recents are keyed to the anonymous uid, never migrated or pruned.** Scope is `selectUid(state)`, which for a signed-out visitor is the Firebase anonymous uid. Observed after one signed-out session: `collection-composer-history:htPQGs6SWdazF6OducW9jNLuihq2`. So recents silently reset on sign-in and on each new anonymous session, orphaned keys accumulate with no cleanup, and the 50-entry cap is per key so it doesn't bound total storage. The history built while browsing anonymously is discarded at the moment the user signs in. — `src/collection-composer-history.ts:30`; `src/actions/collection.ts:189`

- [ ] **Opening any dialog makes the snackbar inert.** `_setSurroundingsInert` walks up through every shadow boundary marking siblings inert; `snack-bar` is a sibling of `main-view` inside `card-web-app`. Verified: with the composer open, `snack-bar.inert === true`. So even after the visibility bug is fixed, Undo would be unclickable whenever a dialog is open. Separately the save/restore is per-instance — two dialogs open in overlapping order each record the other's `wasInert` and correctness depends on close order. *I could not construct a permanently-stuck case in this app*, but nothing enforces the invariant and this is a base class every dialog inherits. — `dialog-element.ts:_setSurroundingsInert`

- [ ] **Focus trap traverses light DOM and shadow DOM on every Tab.** `_focusableElements` recurses into both `child.shadowRoot` and `child`'s own children and separately follows slot assignments, so slotted content can be collected twice; `indexOf` returns the first occurrence, so a duplicate would wrap Tab to the wrong end. *Latent, not live* — measured 12 unique elements with no duplicates in this dialog. Visibility is also only checked via the `hidden` attribute and `aria-hidden`, not computed style. — `dialog-element.ts:_focusableElements`

- [ ] **`https://thecompendium.cards` is hardcoded as a trusted origin in shared code**, in two component literals. Any other deployment inherits an unrelated production domain as trusted, and the diagnostic ("Use a Card Web URL from this app or the production site") is wrong for them. Impact is low — the pasted URL only contributes a same-origin path — but this belongs in config. — `configure-collection-dialog.ts:624`, `:1063`

- [ ] **Listbox structure.** Each `role="option"` button sits inside a plain `<div class="suggestion">` inside `role="listbox"`, breaking the listbox→option ownership chain. `aria-controls` also points at `collection-composer-suggestions` in states where that element isn't rendered. — `configure-collection-dialog.ts:980-994`, `:1023`

---

### Performance

Nothing catastrophic — all avoidable recomputation in the typing path, which is the one path this feature can't afford to feel heavy. Measured in the running app:

| Getter / call | Cost | Called from |
|---|---|---|
| `_parsedSource` | 1.40 ms | render, `_handleSourceInput` (×2), `_handleSourceKeyDown`, `_acceptSourceCompletion` (×2), `_refreshPreviewCounts` — ~4–5× per keystroke in Source mode |
| `_catalogItems` | 0.99 ms | render, plus `_visibleCatalogItems` which calls it again |
| `_composerSuggestions` (50 recents) | 0.74 ms | render, keydown handler, `_refreshPreviewCounts` — each call re-reads localStorage, `JSON.parse`s, and deserialize/serialize round-trips every entry |
| `_composerSuggestions` (1 recent) | 0.14 ms | same |
| `readCollectionComposerMode` | 1.13 µs | card-view render (×3), every keydown, every `stateChanged`. Genuinely negligible — noted only so nobody "optimizes" it. |

- [ ] **Memoize `_parsedSource`, `_catalogItems`, and `_composerSuggestions`** on their inputs. All three are pure and all three are recomputed several times per keystroke.

- [ ] **Preview counts are thrown away and refetched on every keystroke.** `_refreshPreviewCounts` sets `this._previewCounts = {}` before re-enqueuing, and runs on `_composerInput` changes — so every character blanks every count for at least the 150 ms debounce plus a worker round trip, and the primary button relabels between "Open this collection" and "Open 1307 cards", changing width each time. Counts for unchanged suggestions should be retained. — `configure-collection-dialog.ts:1724-1749`

- [ ] **Every collection navigation does a full history read + write synchronously on the main thread.** `recordRecentCollection` runs from `updateCardSelector` — on the critical path of every card and collection navigation — reading and validating the whole stored list (up to 50 `deserialize` + `serialize` round trips) then writing it back, before `updateCollection` dispatches. — `src/actions/collection.ts:184-190`; `collection-composer-history.ts:153`

---

### Scope: engine changes that aren't composer polish

- [ ] **Filter evaluation is now sorted, for every collection in the app.** `combinedFilterForFilterDefinition` evaluates `[...filterDefinition].sort()`. The reasoning in the comment is sound — `serialize()` already sorts, so authoring order shouldn't decide which configurable filter's ranking metadata wins — but this changes result ordering for existing bookmarked and shared URLs combining sort-emitting configurable filters (`query`, `similar`), with no migration note and no test asserting the before/after difference on a real multi-filter description. Worth splitting out and landing on its own. — `src/collection_description.ts:678-687`

- [ ] **A previously dead memo cache is now live.** `memoizedConfigurableFiltersExtras = null` became `= extras`, so configurable filter results are genuinely reused within an `extras` generation instead of recomputed each time. Almost certainly intended and a real speedup — I found no non-deterministic filter factories that would be frozen by it — but it's a live behavior change to the collection engine inside a UI branch. Separately, `makeConfigurableFilter`'s cache key now embeds the current date for relative-date filters, so the map gains an entry per filter per day and is never pruned: harmless in a tab, a slow leak in a long-lived worker. — `collection_description.ts:501-546`; `filters.ts:configurableFilterCacheKey`

---

### Test coverage

All twelve new suites pass individually on Node 20 (151 assertions; the source-grammar coverage is genuinely good):

| Suite | | Suite | |
|---|---|---|---|
| collection-composer-interactions | 41 ✓ | collection-composer-history | 9 ✓ |
| collection-composer-suggestions | 24 ✓ | collection-composer-mode | 9 ✓ |
| collection-source-editor | 23 ✓ | dialog-element | 6 ✓ |
| collection-source | 13 ✓ | navigation-commit | 4 ✓ |
| collection-composer-preview | 11 ✓ | collection-composer-receipt | 4 ✓ |
| collection-filter-catalog | 4 ✓ | collection-composer-draft | 3 ✓ |

The pattern is consistent: each tests the unit in the arrangement the author had in mind.

- [ ] The Enter test types `star` first, so the highlighted row is the intended one. Add coverage for the empty-input state with a populated recents history — the state every user is in after their first Tab.
- [ ] The receipt tests assert `collectionReceiptCanUndo` in isolation. Add a test that renders `snack-bar` and asserts it is actually visible.
- [ ] The dialog focus test supplies a focusable invoker. Add the real case where the invoker isn't focusable.
- [ ] Nothing reads back what a configurable filter's *controls display* after the composer seeds a non-default value — which is why the before/after desync survived a 41-test interaction suite.

Per AGENTS.md's adversarial-review rule, the thesis that lands hardest here is "the tests prove something the product does not actually do."

---

### Suggested order

1. Reflect `active` on `snack-bar`, and stop `_setSurroundingsInert` from catching it. Until this lands, no receipt or Undo can be evaluated at all.
2. Make Enter open the draft — or, if the highlighted row must win, dedupe recents against the active collection and give the already-active close path a message.
3. Fix the `<select>` value binding in `configure-collection-date`. This one is a correctness bug wearing a UI costume.
4. Gate pointer highlighting on real `mousemove`.
5. One pass over every user-facing string: the four names for `starred`, "Add: Add …", "Updated filter", the key hints, "Show N more X filters", the catalog examples' base set.
6. Split the engine changes (sorted filter evaluation, memoization) into their own reviewable change.

---

### Environment note (not this branch's doing, but it blocks dogfooding)

`index.TEMPLATE.html:129` points at `lib/src/components/card-web-app-entry.js`, which does not exist on this branch **or** on `master` — nothing in `src/`, `tools/`, or the npm scripts generates it. `npm run serve` therefore yields a blank page with a 404 on the entry module. I patched the entry to `card-web-app.js` locally to get a running build. Probably worth its own issue.

**Comment by jkomoros** [comment]
## Post-journey-audit bank: remaining spec work and open decisions

Four persona journeys (naive reader, daily gardener, curator, spelunker) were run against the live `codex/collection-composer-polish` build after the 2026-08-22 audit's fixes landed. Everything correctness- or trust-shaped was fixed on the branch. What remains is deliberate feature scope and a few owner decisions, banked here so they don't masquerade as done.

### Spec features not yet built (each observed causing real harm in a journey)

- [ ] **OR authorability in the quick UI.** The curator could not express "tag-3 OR tag-7" anywhere outside hand-typed source grammar, and typing the real `+` syntax into the quick composer is treated as literal text (the `+` silently stripped from the echoed interpretation). Contradicts Decision 6 and §Boolean expression model. Minimum viable: an "Or with…" action on a selected clause; the clause-menu work below is the natural home.
- [ ] **Clause menu verbs.** §Clause editing specifies Change / Invert / Add OR alternative / Remove / Explain this filter / Edit in source; the editor has Change and Remove. Invert matters most: polarity is currently only choosable in the catalog *before* adding.
- [ ] **"Why in this collection?"** (acceptance #18, doctrine req 7). Both the spelunker's anomaly hunt and the curator's "is every card published?" audit needed it; the proof-by-negation trick (add the inverse, read "0 cards") works but is a trick. The partial-match rendering that landed is the cheap first installment.
- [ ] **Count completeness/provenance vocabulary** (§Count preview `CollectionPreview.completeness`): every surface still shows a bare integer. "Exact for N loaded cards" / "at least N" strings.
- [ ] **Per-suggestion "Why this?" / "Show changes"** (§Suggestion anatomy) and representative entering/leaving cards (acceptance #9).
- [ ] **Arrival view leads with the collection** (the naive reader's #1 lever): when a URL carries clauses, the readable sentence + count + invitation should introduce the result set, not the smallest text in the corner over a single card's body. Design-intensive; possibly its own issue.
- [ ] **Broaden suggestions beyond removal** (§Broaden): "widen the date", "make the relationship multi-ply" are specified; only Remove rows exist today.
- [ ] **Distribution affordances**: composed collections lose the drawer's section grouping and offer no tag/section histogram; the spelunker could not answer "where do the 117 cluster?".
- [ ] **Reference-type include/exclude lists** (§Argument editors) — editor is single-select today.
- [ ] **Named/pinned collections** (spec non-goal #6, deferred by design — noting the observed cost: a research session ends holding 5 URLs with only recents to return by).

### Open decisions

- [ ] **Commit-path URL order.** Source mode commits canonical (sorted) order; the quick composer commits authoring order (`serializeShortOriginalOrder`). Both defensible readings of §Canonicalization; they should agree. Decide which the URL bar gets.
- [ ] **Cmd-K's two entries in the canonical shortcut table** (`open-collection-composer` + `find-card-to-link`) — provably disjoint gates today; bless or restructure.
- [ ] **Recents storage keying**: history is keyed to the (possibly anonymous) uid; signing in silently orphans it. Device-scoped vs migrate-on-sign-in.
- [ ] **`configurableFilterCacheKey`** is exported but production-dead after the #743 rebase reconciliation — delete or adopt.
- [ ] **HOUSE-STYLE §2.7** ("The app has no undo, anywhere") needs the collection-navigation receipt recorded as its first exception when this branch lands.

### Known small debts on the branch (named in commit messages, not fixed)

- [ ] Legacy `configure-collection-filter` `<option>` labels still render raw filter ids in the clause editor's select (wider than the composer; touches the legacy builder).
- [ ] `Children`/`Parents` relationship descriptions untouched by the Ancestors/Descendants rewrite.

*(Everything else from the 2026-08-22 audit checklist and the four journey critiques was fixed on the branch and live-verified.)*
